/* COCO-80 class names, in the order YOLOX's class channel indexes them.
 *
 * Generated by tools/gen_coco_labels.py from
 *   YOLOX: yolox/data/datasets/coco_classes.py
 * Do not edit by hand, and do not reorder: index IS the meaning.
 */
#ifndef PLT_IO_COCO_LABELS_H
#define PLT_IO_COCO_LABELS_H

#define PLT_COCO_CLASSES 80

static const char *const plt_coco_labels[PLT_COCO_CLASSES] = {
    "person", "bicycle", "car", "motorcycle",
    "airplane", "bus", "train", "truck",
    "boat", "traffic light", "fire hydrant", "stop sign",
    "parking meter", "bench", "bird", "cat",
    "dog", "horse", "sheep", "cow",
    "elephant", "bear", "zebra", "giraffe",
    "backpack", "umbrella", "handbag", "tie",
    "suitcase", "frisbee", "skis", "snowboard",
    "sports ball", "kite", "baseball bat", "baseball glove",
    "skateboard", "surfboard", "tennis racket", "bottle",
    "wine glass", "cup", "fork", "knife",
    "spoon", "bowl", "banana", "apple",
    "sandwich", "orange", "broccoli", "carrot",
    "hot dog", "pizza", "donut", "cake",
    "chair", "couch", "potted plant", "bed",
    "dining table", "toilet", "tv", "laptop",
    "mouse", "remote", "keyboard", "cell phone",
    "microwave", "oven", "toaster", "sink",
    "refrigerator", "book", "clock", "vase",
    "scissors", "teddy bear", "hair drier", "toothbrush",
};

/* Safe for any index the decoder can produce. */
static inline const char *plt_coco_label(int cls)
{
    return (cls >= 0 && cls < PLT_COCO_CLASSES) ? plt_coco_labels[cls] : "?";
}

#endif /* PLT_IO_COCO_LABELS_H */
